#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'
DIM='\033[2m'

# Get current directory
CURRENT_DIR=$(pwd)
FEATURE_NAME=$(basename "$CURRENT_DIR")

echo -e "${BOLD}${CYAN}╔════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║     Git Worktree - Agent Context       ║${NC}"
echo -e "${BOLD}${CYAN}╚════════════════════════════════════════╝${NC}"
echo ""

# Check if we're in a worktree directory (should contain repo subdirectories with .git files)
REPOS=()
for dir in "$CURRENT_DIR"/*/; do
    if [ -d "$dir" ]; then
        if [ -f "$dir/.git" ] || [ -d "$dir/.git" ]; then
            repo_name=$(basename "$dir")
            REPOS+=("$repo_name")
        fi
    fi
done

if [ ${#REPOS[@]} -eq 0 ]; then
    echo -e "${RED}Error: No git worktrees found in current directory.${NC}"
    echo -e "${CYAN}Make sure you're inside a worktree feature directory.${NC}"
    echo ""
    echo -e "${DIM}Expected structure:${NC}"
    echo -e "${DIM}  worktrees/${NC}"
    echo -e "${DIM}    └── feature-branch-name/  ${CYAN}← Run wt-agent here${NC}"
    echo -e "${DIM}        ├── repo-1/${NC}"
    echo -e "${DIM}        └── repo-2/${NC}"
    exit 1
fi

echo -e "${BOLD}Feature:${NC} ${CYAN}$FEATURE_NAME${NC}"
echo ""
echo -e "${BOLD}Repositories in this worktree:${NC}"
for repo in "${REPOS[@]}"; do
    # Get branch name from repo
    branch_name=""
    if [ -f "$CURRENT_DIR/$repo/.git" ]; then
        branch_name=$(cd "$CURRENT_DIR/$repo" && git rev-parse --abbrev-ref HEAD 2>/dev/null)
    fi
    echo -e "  ${GREEN}→${NC} $repo ${DIM}($branch_name)${NC}"
done
echo ""

# Check if AGENTS.md already exists
if [ -f "$CURRENT_DIR/AGENTS.md" ]; then
    echo -e "${YELLOW}⚠${NC}  AGENTS.md already exists."
    read -p "$(echo -e "Overwrite? [y/N]: ")" OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo -e "${CYAN}Cancelled.${NC}"
        exit 0
    fi
    echo ""
fi

# Get description from user
echo -e "${BOLD}Describe what you're working on:${NC}"
echo -e "${DIM}(Brief description of the feature, fix, or refactor)${NC}"
echo ""
read -p "> " DESCRIPTION

if [ -z "$DESCRIPTION" ]; then
    echo -e "${RED}Description cannot be empty.${NC}"
    exit 1
fi

echo ""
echo -e "${CYAN}→${NC} Generating AGENTS.md..."

# Get branch name (use first repo's branch as reference)
BRANCH_NAME=""
if [ ${#REPOS[@]} -gt 0 ]; then
    BRANCH_NAME=$(cd "$CURRENT_DIR/${REPOS[0]}" && git rev-parse --abbrev-ref HEAD 2>/dev/null)
fi

# Build repos list for markdown
REPOS_MD=""
for repo in "${REPOS[@]}"; do
    branch=$(cd "$CURRENT_DIR/$repo" && git rev-parse --abbrev-ref HEAD 2>/dev/null)
    REPOS_MD="${REPOS_MD}- \`${repo}/\` - Branch: \`${branch}\`
"
done

# Generate AGENTS.md
cat > "$CURRENT_DIR/AGENTS.md" << EOF
# Agent Context

> This file provides context for AI coding assistants (Claude, Cursor, GitHub Copilot, etc.)

## 🎯 Current Task

**${DESCRIPTION}**

## 📍 Location

You are working inside a **git worktree** - an isolated workspace for this specific task.

- **Feature Directory:** \`${FEATURE_NAME}\`
- **Branch:** \`${BRANCH_NAME}\`

## 📦 Available Repositories

${REPOS_MD}

## 🔧 Worktree Structure

This is a multi-repo worktree setup. Each subdirectory is a separate git repository, all checked out to the same feature branch.

\`\`\`
${FEATURE_NAME}/
├── AGENTS.md              ← You are here
EOF

# Add repos to structure
for repo in "${REPOS[@]}"; do
    echo "├── ${repo}/" >> "$CURRENT_DIR/AGENTS.md"
done

# Continue the file
cat >> "$CURRENT_DIR/AGENTS.md" << EOF
└── ${FEATURE_NAME}.code-workspace
\`\`\`

## 💡 Guidelines

1. **Scope**: All changes should be related to: *${DESCRIPTION}*
2. **Branch**: You're on \`${BRANCH_NAME}\` - commit directly here
3. **Multi-repo**: If the task spans frontend and backend, coordinate changes across repos
4. **Testing**: Run tests in each affected repo before committing

## 🚀 Quick Commands

\`\`\`bash
# Navigate between repos
cd ${REPOS[0]}/

# Check git status across all repos
for d in */; do echo "=== \$d ===" && (cd "\$d" && git status -s); done

# Commit in current repo
git add . && git commit -m "feat: description"

# Push all repos
for d in */; do (cd "\$d" && git push origin ${BRANCH_NAME}); done
\`\`\`

## 📝 Notes

<!-- Add any additional context, decisions, or notes here -->

---

*Generated by wt-agent on $(date "+%Y-%m-%d %H:%M")*
EOF

echo -e "${GREEN}✓${NC} AGENTS.md created"
echo ""
echo -e "${BOLD}${GREEN}✓ Agent context ready!${NC}"
echo ""
echo -e "${CYAN}The AGENTS.md file provides context for AI assistants about:${NC}"
echo -e "  • What you're working on"
echo -e "  • Which repos are available"
echo -e "  • The worktree structure"
echo -e "  • Helpful commands"
echo ""
echo -e "${DIM}Tip: AI tools like Claude Code, Cursor, and Copilot will use this context.${NC}"
echo ""
